const category = [
  { id: "1", name: "Women-Ethnic" },
  { id: "2", name: "Women-Western" },
  { id: "3", name: "Men" },
  { id: "4", name: "Kids" },
  {id:"5", name:"Home & Kitchen"},
  {id:"6", name:"Beauty & Health"}
]

const product = [
  {
    id: "1",
    title: "Elegant Cotton Kurti",
    description: "Beautiful cotton kurti with traditional prints for daily wear.",
    price: 799,
    discountPercentage: 15,
    rating: 4.3,
    stock: 120,
    brand: "Fabindia",
    category: "Women-Ethnic",
    subcategory: "Kurtis",
    thumbnail: "https://example.com/images/kurti1.jpg",
    images: "https://images.meesho.com/images/products/383853457/i9ylu_1200.jpg"
  },
  {
    id: "2",
    title: "Designer Silk Saree",
    description: "Premium quality silk saree perfect for weddings and parties.",
    price: 2499,
    discountPercentage: 25,
    rating: 4.6,
    stock: 60,
    brand: "Suta",
    category: "Women-Ethnic",
    subcategory: "Sarees",
    thumbnail: "https://example.com/images/saree1.jpg",
    images: "https://sudathi.com/cdn/shop/files/4294S261_1.jpg?v=1743227166&width=1100"
  },
  {
    id: "3",
    title: "Chikankari Kurta Set",
    description: "Elegant white chikankari kurta set with matching pants.",
    price: 1599,
    discountPercentage: 18,
    rating: 4.5,
    stock: 80,
    brand: "W for Woman",
    category: "Women-Ethnic",
    subcategory: "Kurta Sets",
    thumbnail: "https://example.com/images/kurta_set1.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTUYIRlNJO5do-OE59y72DnveVYmCpamv1vOEflcuILJQKbr3dzaw4xhdIzSeF2E-Eh3DriptjcWw5jB9dk3mLUDzBU_KasrHyRWWHNvxvlDh9eNVk2g20i&usqp=CAc"
  },
  {
    id: "4",
    title: "Banarasi Silk Dupatta",
    description: "Rich Banarasi silk dupatta with intricate zari work.",
    price: 999,
    discountPercentage: 30,
    rating: 4.7,
    stock: 45,
    brand: "Soch",
    category: "Women-Ethnic",
    subcategory: "Dupattas",
    thumbnail: "https://example.com/images/dupatta1.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTVEG9oT-VFQufx_fAvKyJ2AoOSYk4AT52IRcdbRVA4LzfybN6uTl5Ld9Hl3NbyX7nNaEKOWIyv0VWYuBZkIOylQuxuW3OGbuLkOsCsyppzMf8PvDFR1KIS2g"
  },
  {
    id: "5",
    title: "Leheriya Printed Kurta",
    description: "Stylish leheriya printed cotton kurta for casual outings.",
    price: 699,
    discountPercentage: 20,
    rating: 4.1,
    stock: 150,
    brand: "Biba",
    category: "Women-Ethnic",
    subcategory: "Kurtis",
    thumbnail: "https://example.com/images/kurti2.jpg",
    images: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR_SSOU9hoRn1p3SAjGLq-hlnwCLfr2miZ2RM3WBDdYj-N_rDOoyWxzX0tR4zO9lEUr2GFmqUyFcj_HuJ6u7ZgLKPun3KzkPbvkqNOmDgqrWxeEObtXpQfRCs4"
  },
  {
    id: "6",
    title: "Phulkari Embroidered Dupatta",
    description: "Colorful phulkari embroidery dupatta to uplift your ethnic style.",
    price: 849,
    discountPercentage: 22,
    rating: 4.4,
    stock: 90,
    brand: "Rangriti",
    category: "Women-Ethnic",
    subcategory: "Dupattas",
    thumbnail: "https://example.com/images/dupatta2.jpg",
    images: "https://assetscdn1.paytm.com/images/catalog/product/A/AP/APPPHULKARI-EMBONA-47196F50848E7/1562965122102_0..jpg"
  },
  {
    id: "7",
    title: "Zari Woven Saree",
    description: "Traditional zari woven silk saree with rich patterns.",
    price: 3199,
    discountPercentage: 28,
    rating: 4.5,
    stock: 55,
    brand: "Pothys",
    category: "Women-Ethnic",
    subcategory: "Sarees",
    thumbnail: "https://example.com/images/saree2.jpg",
    images: "https://www.jaipurkurti.com/cdn/shop/files/1_bbf56231-41ad-484c-bb49-f5c7f9e3ce5c.jpg?v=1745338833"
  },
  {
    id: "8",
    title: "Printed Anarkali Kurta",
    description: "Graceful anarkali kurta with ethnic floral prints.",
    price: 1199,
    discountPercentage: 19,
    rating: 4.2,
    stock: 110,
    brand: "Global Desi",
    category: "Women-Ethnic",
    subcategory: "Anarkalis",
    thumbnail: "https://example.com/images/anarkali1.jpg",
    images: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ5rTWtxCivRAnVtyyChbwa7Xp9qkDFC2bbKVaTPKJghPHXe_uQA4iUUqe0BnDjjqKGgD_T5m1UUBLbHz7WNNfUwk_N5x3xH2zSY73U-Loc"
  },
  {
    id: "9",
    title: "Georgette Sharara Set",
    description: "Trendy georgette sharara suit set perfect for festive occasions.",
    price: 1899,
    discountPercentage: 25,
    rating: 4.3,
    stock: 65,
    brand: "Libas",
    category: "Women-Ethnic",
    subcategory: "Sharara Sets",
    thumbnail: "https://example.com/images/sharara1.jpg",
    images: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSoGU05aa32KSAMVkPEOLRJIRoYOsC4axt_uHXqgkMAGcSd2FcNon1G3vO1uMCuJumyxgXE0f7PEFVzgINqib-YKRUoxgNHxhCmVJP7Y5y4"
  },
  {
    id: "10",
    title: "Embroidered Kurti",
    description: "Elegant embroidered kurti made from fine rayon fabric.",
    price: 999,
    discountPercentage: 20,
    rating: 4,
    stock: 100,
    brand: "Aurelia",
    category: "Women-Ethnic",
    subcategory: "Kurtis",
    thumbnail: "https://example.com/images/kurti3.jpg",
    images: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcR8l-onn0fZ-5Q1LLE83p4ePJB1CQjNWAyRPRm87-oahKw5i4xPxbeC3AD713N3XEOi5Byfc-pjfWCqloZVu8U3W1ZkPHil6DgyqgxFSks"
  },
  {
    id: 11,
    title: "Festive Net Lehenga",
    description: "Beautiful net lehenga with intricate embroidery for festive occasions.",
    price: 3299,
    discountPercentage: 30,
    rating: 4.5,
    stock: 40,
    brand: "Manyavar Mohey",
    category: "Women-Ethnic",
    subcategory: "Lehengas",
    thumbnail: "https://example.com/images/lehenga1.jpg",
    images: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTkGh4WKIRz0f3Wv0fS0FOfQXLJ_nQFOI3ntrDgbJNBZjRu5UZlCWVK1XsoO6nbivqu1DCHz8kZa6vyVhmpWXS7C3aZcurfQwaRLIO7GQM"
  },
  {
    id: 12,
    title: "Chanderi Silk Kurti",
    description: "Premium chanderi silk kurti with hand block prints.",
    price: 1699,
    discountPercentage: 18,
    rating: 4.4,
    stock: 75,
    brand: "Biba",
    category: "Women-Ethnic",
    subcategory: "Kurtis",
    thumbnail: "https://example.com/images/kurti4.jpg",
    images: "https://images.meesho.com/images/products/481044022/jwag2_1200.jpg"
  },
  {
    id: 13,
    title: "Velvet Bridal Dupatta",
    description: "Luxurious red velvet bridal dupatta with heavy golden embroidery.",
    price: 2199,
    discountPercentage: 22,
    rating: 4.7,
    stock: 30,
    brand: "Pernia's Pop Up",
    category: "Women-Ethnic",
    subcategory: "Dupattas",
    thumbnail: "https://example.com/images/dupatta3.jpg",
    images: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_RaVomLKF-xsob3D34ON2hpEThZjG-agVAJ9n1NPr6WQVIV5OWI0x8mI&s"
  },
  {
    id: 14,
    title: "Handloom Cotton Saree",
    description: "Eco-friendly handwoven cotton saree perfect for summer.",
    price: 1899,
    discountPercentage: 20,
    rating: 4.3,
    stock: 85,
    brand: "Indya",
    category: "Women-Ethnic",
    subcategory: "Sarees",
    thumbnail: "https://example.com/images/saree3.jpg",
    images: "https://d1311wbk6unapo.cloudfront.net/NushopCatalogue/tr:f-webp,w-1200,fo-auto/64f99a0ad51f9400133b0914/cat_img/N_wer71B_PHUDC6TV1I_2024-12-18_1.jpg"
  },
  {
    id: 15,
    title: "Pastel Anarkali Gown",
    description: "Stylish pastel colored anarkali gown for cocktail and reception.",
    price: 4499,
    discountPercentage: 27,
    rating: 4.5,
    stock: 35,
    brand: "Global Desi",
    category: "Women-Ethnic",
    subcategory: "Anarkalis",
    thumbnail: "https://example.com/images/anarkali2.jpg",
    images: "https://cdn-appdata.seasonsindia.com/uploads/feature_images/IMG_5020.jpg"
  },
  {
    id: 16,
    title: "Printed Sharara Kurta Set",
    description: "Lightweight rayon sharara set with trendy floral prints.",
    price: 2099,
    discountPercentage: 24,
    rating: 4.2,
    stock: 50,
    brand: "W for Woman",
    category: "Women-Ethnic",
    subcategory: "Sharara Sets",
    thumbnail: "https://example.com/images/sharara2.jpg",
    images: "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/s/h/shy_2064ks-1.jpg?rnd=20200526195200&tr=w-1080"
  },
  {
    id: 17,
    title: "Silk Blend Saree",
    description: "Light silk blend saree ideal for office and casual wear.",
    price: 1599,
    discountPercentage: 17,
    rating: 4.1,
    stock: 95,
    brand: "Suta",
    category: "Women-Ethnic",
    subcategory: "Sarees",
    thumbnail: "https://example.com/images/saree4.jpg",
    images: "https://sudathi.com/cdn/shop/files/4294S261_1.jpg?v=1743227166&width=1100"
  },
  {
    id: 18,
    title: "Printed Palazzo Set",
    description: "Trendy cotton printed palazzo set with block prints.",
    price: 1399,
    discountPercentage: 20,
    rating: 4,
    stock: 130,
    brand: "Rangriti",
    category: "Women-Ethnic",
    subcategory: "Palazzo Sets",
    thumbnail: "https://example.com/images/palazzo1.jpg",
    images: "https://images.meesho.com/images/products/497890595/7bb2h_1200.jpg"
  },
  {
    id: 19,
    title: "Net Embroidered Gown",
    description: "Beautiful net embroidered gown with sequin detailing.",
    price: 4999,
    discountPercentage: 32,
    rating: 4.6,
    stock: 28,
    brand: "Pernia's Pop Up",
    category: "Women-Ethnic",
    subcategory: "Gowns",
    thumbnail: "https://example.com/images/gown1.jpg",
    images: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTHY8E8guwFiEzV8Pt63GLXlLFN1a8INKn0f3eRXbNYa8x3vpd6ht8mSTZOyGNbhLjfP5Sc6bGd7ht3F83VA4jFWWO8exe7yWKfsd08OHTo"
  },
  {
    id: 20,
    title: "Velvet Ethnic Jacket",
    description: "Royal velvet ethnic jacket to pair with kurtis and suits.",
    price: 2499,
    discountPercentage: 23,
    rating: 4.5,
    stock: 40,
    brand: "Manyavar Mohey",
    category: "Women-Ethnic",
    subcategory: "Ethnic Jackets",
    thumbnail: "https://example.com/images/jacket1.jpg",
    images: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ6fMg0G9bsxoh_nHspx5DvdjoIZUchrSRhQvLps9po2wtymeRvIV-qx8sza8v98yKgd7EOsMnsqBWjZXyOulr7DtjRy3oQ8MtiF616MWM"
  },




  {
    id: 1,
    title: "Stylish Denim Jacket",
    description: "Trendy denim jacket perfect for casual outings.",
    price: 1799,
    discountPercentage: 20,
    rating: 4.4,
    stock: 80,
    brand: "Only",
    category: "Women-Western",
    subcategory: "Jackets",
    thumbnail: "https://example.com/images/jacket1.jpg",
    images:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSHNBmXynWE-H4hYSbcnParekboQo2M_2-llcPXFa5dfrhzwxrducpOb6TfYIahm2dZ0c3QeHHXrha6nfwHR7RfxttqPWTZ-TDIZwjgm00BCXBC_1PW_d3V"

  },
  {
    id: 2,
    title: "Floral Maxi Dress",
    description: "Elegant floral printed maxi dress for summer.",
    price: 2499,
    discountPercentage: 25,
    rating: 4.5,
    stock: 70,
    brand: "AND",
    category: "Women-Western",
    subcategory: "Dresses",
    thumbnail: "https://example.com/images/dress1.jpg",
    images:
      "https://ladybaazar.com/cdn/shop/files/Floral_Print_V-Neck_Maxi_Fit_and_Flare_Dress3.jpg?v=1719061425"

  },
  {
    id: 3,
    title: "High-Waist Skinny Jeans",
    description: "Comfortable high-rise skinny jeans for everyday style.",
    price: 2099,
    discountPercentage: 18,
    rating: 4.2,
    stock: 90,
    brand: "Levi's",
    category: "Women-Western",
    subcategory: "Jeans",
    thumbnail: "https://example.com/images/jeans1.jpg",
    images:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSJPM9bYIxqfeZgAI7z6vRC35RQoY-Bq4U685w4ghjP-WZXMAK9DMfb09eD4yLnTteLjNaQmp7RqGVur9CF2x-UN3ocXthDwtaL3ZVvzqA"

  },
  {
    id: 4,
    title: "Casual Striped Shirt",
    description: "Soft cotton striped shirt for a relaxed look.",
    price: 1399,
    discountPercentage: 22,
    rating: 4.1,
    stock: 100,
    brand: "H&M",
    category: "Women-Western",
    subcategory: "Shirts",
    thumbnail: "https://example.com/images/shirt1.jpg",
    images:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRAAXNaApBpByZW0hIAG60kDqRKYR9uzuYy0IeKGaAWlzl2L-iT8qSHNfhGEebj4WQlCa1oV18-ijPxf5RGkBpyhpisbtPQWoUp9kmGczrj"

  },
  {
    id: 5,
    title: "Crop Top with Puff Sleeves",
    description: "Trendy puff-sleeve crop top for a chic vibe.",
    price: 999,
    discountPercentage: 20,
    rating: 4.3,
    stock: 120,
    brand: "Forever 21",
    category: "Women-Western",
    subcategory: "Tops",
    thumbnail: "https://example.com/images/top1.jpg",
    images:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRGA_4d1zrJN3nN6CDvoNXgzyM53CwQSfg2kDGR7PI8ralDBN80XAs-b_XldMlUpWVIsV56wSlUJy_RMm1-aRrlN5aUpIvF0XQ3L8E6lYec"

  },
  {
    id: 6,
    title: "Black Faux Leather Skirt",
    description: "Stylish faux leather mini skirt perfect for parties.",
    price: 1899,
    discountPercentage: 23,
    rating: 4.5,
    stock: 60,
    brand: "Zara",
    category: "Women-Western",
    subcategory: "Skirts",
    thumbnail: "https://example.com/images/skirt1.jpg",
    images:
      "https://images.meesho.com/images/products/456093191/tss2x_512.webp"

  },
  {
    id: 7,
    title: "Basic White T-Shirt",
    description: "Soft and breathable white cotton t-shirt.",
    price: 599,
    discountPercentage: 15,
    rating: 4.0,
    stock: 200,
    brand: "Uniqlo",
    category: "Women-Western",
    subcategory: "T-Shirts",
    thumbnail: "https://example.com/images/tshirt1.jpg",
    images:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQee47o1gunaJtLusP7n3NbJpxbmZB7d72x0Zi5P3M2ws2Fj6IM5qJO4SwqS6bFcHqN4FZH6LnT-D1uvZnAFaOgfb2ZCex9r3G_U0u700Gu"

  },
  {
    id: 8,
    title: "Ripped Boyfriend Jeans",
    description: "Comfort-fit ripped boyfriend jeans for street style.",
    price: 2299,
    discountPercentage: 20,
    rating: 4.2,
    stock: 75,
    brand: "Pepe Jeans",
    category: "Women-Western",
    subcategory: "Jeans",
    thumbnail: "https://example.com/images/jeans2.jpg",
    images:
      "https://images.meesho.com/images/products/402882210/6wrnv_1200.jpg"

  },
  {
    id: 9,
    title: "Knitted Winter Sweater",
    description: "Cozy knitted sweater ideal for winter wear.",
    price: 2199,
    discountPercentage: 28,
    rating: 4.6,
    stock: 50,
    brand: "Mango",
    category: "Women-Western",
    subcategory: "Sweaters",
    thumbnail: "https://example.com/images/sweater1.jpg",
    images:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRHGlhWeFHkX5kxBJfOxVkLMnI4rB2Zu5zAGlKwq2N3kdtTHbxuUjI_Db6Ht3-1WB0zRe_ZJdp-Ytx128mysTq5mFoDDzqkEbD5a8KQP90"

  },
  {
    id: 10,
    title: "Pleated Mini Skirt",
    description: "Cute pleated mini skirt with side zip closure.",
    price: 1599,
    discountPercentage: 18,
    rating: 4.1,
    stock: 90,
    brand: "H&M",
    category: "Women-Western",
    subcategory: "Skirts",
    thumbnail: "https://example.com/images/skirt2.jpg",
    images:
      "https://m.media-amazon.com/images/I/81KKovZ36IL._AC_UY1100_.jpg"

  },
  {
    id: 11,
    title: "Button Down Denim Dress",
    description: "Chic denim dress with front button detailing.",
    price: 2799,
    discountPercentage: 26,
    rating: 4.5,
    stock: 40,
    brand: "Only",
    category: "Women-Western",
    subcategory: "Dresses",
    thumbnail: "https://example.com/images/dress2.jpg",
    images:
      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSJ3T-SLQQ_TMcO355tzMeB7htFmmTYuyVspaVF3j86uogaJip2COyBxX1GJQZfStVHINDRkeeduMFI7t-OjBIYfGR7Nv2KJ_81f2ZYt4wcKLszG3w9dHpC8mBZVSYIXzWfR7M2ng&usqp=CAc"

  },
  {
    id: 12,
    title: "Sleeveless Ruffle Top",
    description: "Cute sleeveless ruffle top for summer brunches.",
    price: 1099,
    discountPercentage: 21,
    rating: 4.3,
    stock: 110,
    brand: "Zara",
    category: "Women-Western",
    subcategory: "Tops",
    thumbnail: "https://example.com/images/top2.jpg",
    images:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS2u6M-7f1QZmkL5z69eiss30swqxiULmY_PdDUAjj_qmMU-ETxoI3-p95ZzX6ShHxSoOwBCwN2_Q31b-jy0aQ-BHsAWD8o25MCtlGl8sk6POxM8NElZ1Lhdg&usqp=CAc"

  },
  {
    id: 13,
    title: "Relaxed Fit Blazer",
    description: "Sophisticated blazer for a boss-lady look.",
    price: 3499,
    discountPercentage: 30,
    rating: 4.6,
    stock: 35,
    brand: "Mango",
    category: "Women-Western",
    subcategory: "Blazers",
    thumbnail: "https://example.com/images/blazer1.jpg",
    images:
      "https://images.meesho.com/images/products/472560848/fqhgp_1200.jpg"

  },
  {
    id: 14,
    title: "Polka Dot Wrap Dress",
    description: "Elegant polka dot wrap dress for a retro vibe.",
    price: 2399,
    discountPercentage: 24,
    rating: 4.5,
    stock: 55,
    brand: "Forever 21",
    category: "Women-Western",
    subcategory: "Dresses",
    thumbnail: "https://example.com/images/dress3.jpg",
    images:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTFCJOk70yHzTtfJ7xQ3DCeo6xWnP-oncyiPl_W33luGs-IRJgBVIcsIDefLwEYznNZaMXDwWrBXtbQJ1xSlPx5wArzvLtJi1lsyNk2XZ4"

  },
  {
    id: 15,
    title: "Sequin Party Top",
    description: "Shimmering sequin top perfect for parties.",
    price: 1799,
    discountPercentage: 22,
    rating: 4.4,
    stock: 60,
    brand: "AND",
    category: "Women-Western",
    subcategory: "Tops",
    thumbnail: "https://example.com/images/top3.jpg",
    images:
      "https://images.meesho.com/images/products/250122965/wghbh_1200.jpg"

  },
  {
    id: 16,
    title: "Striped Culottes",
    description: "Relaxed fit striped culottes for effortless style.",
    price: 1599,
    discountPercentage: 19,
    rating: 4.2,
    stock: 95,
    brand: "Bershka",
    category: "Women-Western",
    subcategory: "Culottes",
    thumbnail: "https://example.com/images/culottes1.jpg",
    images:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT-ytnNszccuFv2_9G8UAJ1KGeIOxAH8C53ghkRvqzdTluH2T4tGtGcj-N26NOj9oukf_Tvtt0uuYGCnCzh2CYazSgrnzu23JGXEO8fhv4"

  },
  {
    id: 17,
    title: "Ribbed Bodycon Dress",
    description: "Fitted ribbed bodycon dress for a sleek look.",
    price: 1999,
    discountPercentage: 20,
    rating: 4.5,
    stock: 70,
    brand: "H&M",
    category: "Women-Western",
    subcategory: "Dresses",
    thumbnail: "https://example.com/images/dress4.jpg",
    images:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRYY2qL4Mlk85Z22ex0EdeUM5rjzQ_g656Igu0vMEf_6B3VaPn0xDtLRw6iNCZzX2LUuE4J0onrIuFGs65dDGMJwPCYTFtSufNiOu4FbaE"

  },
  {
    id: 18,
    title: "Oversized Graphic Tee",
    description: "Cool oversized t-shirt with graphic print.",
    price: 899,
    discountPercentage: 16,
    rating: 4.1,
    stock: 150,
    brand: "Pull & Bear",
    category: "Women-Western",
    subcategory: "T-Shirts",
    thumbnail: "https://example.com/images/tshirt2.jpg",
    images:
      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQwo9H-YqbcuZKkQYBkuOJuHWv8okjEPbsIntbOZHJBMj4LPbMcyJp2lL_qqohOnWnERhyHrhp_JnrRK_0NgiIfylaml1vzRBiYhGDNOffvkIjjKXToLnhT9w"

  },
  {
    id: 19,
    title: "Formal Trousers",
    description: "High-waisted tailored trousers for formal events.",
    price: 2599,
    discountPercentage: 27,
    rating: 4.5,
    stock: 65,
    brand: "Mango",
    category: "Women-Western",
    subcategory: "Trousers",
    thumbnail: "https://example.com/images/trousers1.jpg",
    images:
      "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTWiEAQxmgWd4gu9Zg7VbIHxW862_J2WdrVXFVFMYW5cygp2J-B9Vpzy1jXnJCrIuhhKQHT2iDwG8zzQ2SvxZfW-5BNI31e1PUwpiXNQ7_UsuJ4upVxWNvs"

  },
  {
    id: 20,
    title: "Sheer Mesh Top",
    description: "Trendy sheer mesh top for clubbing nights.",
    price: 1299,
    discountPercentage: 21,
    rating: 4.3,
    stock: 85,
    brand: "Zara",
    category: "Women-Western",
    subcategory: "Tops",
    thumbnail: "https://example.com/images/top4.jpg",
    images:
      "https://images.meesho.com/images/products/439303540/iu8fh_1200.jpg"

  },

  {
    id: 1,
    title: "Men's Casual Shirt",
    description: "Comfortable and stylish shirt for daily wear",
    price: 29.99,
    discountPercentage: 10,
    rating: 4.5,
    stock: 150,
    brand: "Brand A",
    category: "Men",
    subcategory: "Shirts",
    thumbnail: "https://example.com/thumbnail1.jpg",
    images: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQTGEZ8GkBOo6BAIk6bvudu8CfWUG0S4RyjKaCMMtcjR1PCgFRerwP5ebFfquZtpu_CjDuw6_vDT08xdDQ3ejtF3_AJTidxjhlw4E7mHw8gRg-M1poznLgHyA"
  },
  {
    id: 2,
    title: "Men's Running Shoes",
    description: "Lightweight and durable shoes for sports",
    price: 59.99,
    discountPercentage: 15,
    rating: 4.7,
    stock: 100,
    brand: "Brand B",
    category: "Men",
    subcategory: "Sports Shoes",
    thumbnail: "https://example.com/thumbnail2.jpg",
    images: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQulVrcP3GBRhPWCQv_KpU-FfIeS1uTSUG632PbdFM9YM9PvmfL6WI_OGDw-_xcdAvBHlUgX0evWVQmwWlfwEYEUDXwuVKw1wBbJfchu_Yvj3M_d2vLTBJGAPDJHc9H2P2IFuSjBzAB734&usqp=CAc"
  },
  {
    id: 3,
    title: "Leather Wallet",
    description: "Stylish leather wallet for everyday use",
    price: 49.99,
    discountPercentage: 5,
    rating: 4.2,
    stock: 200,
    brand: "Brand C",
    category: "Men",
    subcategory: "Wallets",
    thumbnail: "https://example.com/thumbnail3.jpg",
    images: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQPR4jPma0UIoK7oS7-QMaxyYDFjPFITEZZgJKAZRManUzY4wiAK7-YiL4UnhTjXceA2KtcUdw6lVOv0biy_XI2MJQlBnzCas5VsHFtbamqEis7_Zcd1-YNtw"
  },
  {
    id: 4,
    title: "Men's Jeans",
    description: "Comfortable denim jeans for casual wear",
    price: 39.99,
    discountPercentage: 20,
    rating: 4.8,
    stock: 120,
    brand: "Brand D",
    category: "Men",
    subcategory: "Jeans",
    thumbnail: "https://example.com/thumbnail4.jpg",
    images: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQFZxikKstmD42NKvwTyna7ydLJ799z61ILNYPq5kegO7D7lPWnSAmff1Oc_YeeH8X4YXlIHclUbjQ9UGONu2dmQ98KyZXLrEfTZBbvbJPSj6XW0CdWDjlw"
  },
  {
    id: 5,
    title: "Men's Watch",
    description: "Stylish wristwatch with a modern design",
    price: 129.99,
    discountPercentage: 10,
    rating: 4.3,
    stock: 80,
    brand: "Brand E",
    category: "Men",
    subcategory: "Watches",
    thumbnail: "https://example.com/thumbnail5.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT6fRaUvyAVadUj0OcxpkgYaxV3v1pOj2ZTljYEgnUkTnA-RibPTBmSSTkdmFCt2VoW8NSXXPTvgHgtHIO248Y_vVwgBowl_P0Xw4fb3z7p"
  },
  {
    id: 6,
    title: "Men's T-Shirt",
    description: "Basic cotton t-shirt for everyday use",
    price: 19.99,
    discountPercentage: 15,
    rating: 4.4,
    stock: 300,
    brand: "Brand F",
    category: "Men",
    subcategory: "T-Shirts",
    thumbnail: "https://example.com/thumbnail6.jpg",
    images: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQIihEV7XG8M5_fUzc6ChFnPz9kY0G6pNznPsFYRHcDT3eLZyCNqbnrBF8bhGxeB_oCGXkOkPFwggCkOlbP5RgaIIAtYolvwrM_x0tr2q8NX7ZQk5JwVu5s"
  },
  {
    id: 7,
    title: "Men's Sneakers",
    description: "Comfortable sneakers for casual and sports use",
    price: 69.99,
    discountPercentage: 8,
    rating: 4.6,
    stock: 50,
    brand: "Brand G",
    category: "Men",
    subcategory: "Casual Shoes",
    thumbnail: "https://example.com/thumbnail7.jpg",
    images: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRTimMYXpPfx9rVSDEY328MRp5WVKxQZ7GXFCdhLNpmFLzOD2btZLTCetsYoCArX4vWi7K4JOcd9VwjgWvDRdG3siXokSF3CYG7eKkGtQBsCJGxwcBCEenV"
  },
  {
    id: 8,
    title: "Men's Sunglasses",
    description: "UV-protection sunglasses with a trendy design",
    price: 39.99,
    discountPercentage: 12,
    rating: 4.1,
    stock: 100,
    brand: "Brand H",
    category: "Men",
    subcategory: "Sunglasses",
    thumbnail: "https://example.com/thumbnail8.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT9WfunGJcobZENgH1J7sinuGMlEaFixBvvpqk1Zgk1BAW9K6f4YdWTaK2lS3oN35mI4OWRyLkLU1JV3onfGaenco_YhQTyIvvEZHB-bTk"
  },
  {
    id: 9,
    title: "Men's Hoodie",
    description: "Cozy hoodie for cool weather",
    price: 49.99,
    discountPercentage: 10,
    rating: 4.7,
    stock: 90,
    brand: "Brand I",
    category: "Men",
    subcategory: "Hoodies",
    thumbnail: "https://example.com/thumbnail9.jpg",
    images: "https://campussutra.com/cdn/shop/products/AWIN21_HHH_M_PLN_BLGR_F.webp?v=1661863853"
  },
  {
    id: 10,
    title: "Men's Backpack",
    description: "Spacious and stylish backpack for daily use",
    price: 59.99,
    discountPercentage: 15,
    rating: 4.5,
    stock: 200,
    brand: "Brand J",
    category: "Men",
    subcategory: "Bags",
    thumbnail: "https://example.com/thumbnail10.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRPeU847yFA7kA7pn7viznudpqvtCMn7o0Tth36YfJJ3nwTpt8iJ4pnNXOimkF4jlsOxQ8aXwpJyTdWoA0S8c3itDgGp9YsTVDPbqO5g1T5NH_5D-fpFvg7GQ"
  },
  {
    id: 11,
    title: "Men's Blazer",
    description: "Elegant blazer for formal occasions",
    price: 199.99,
    discountPercentage: 5,
    rating: 4.8,
    stock: 60,
    brand: "Brand K",
    category: "Men",
    subcategory: "Blazers",
    thumbnail: "https://example.com/thumbnail11.jpg",
    images: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQjPWgSJ8WFbStlPPr5gEY1bnCSNiicaLMgtQRALfHuCuGKNy3J4DzPDkFW8y_GkCzbc0Vgso_gWOb6CXg66Fhk985fYiFy4NZ3IEV8lrYTWY5WgNcknhmj"
  },
  {
    id: 12,
    title: "Men's Jacket",
    description: "Stylish and warm jacket for winter",
    price: 129.99,
    discountPercentage: 10,
    rating: 4.4,
    stock: 150,
    brand: "Brand L",
    category: "Men",
    subcategory: "Jackets",
    thumbnail: "https://example.com/thumbnail12.jpg",
    images: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTkmLieVAjvjv96EBuEaxWmH0TaDbZzQzbVJpOz4UFCibGEoDP3zEvp7LylUM7sBVwKL2yOKDHPWZf1jrOJ2CBWghA6JbPWokpJf-meqn8"
  },
  {
    id: 13,
    title: "Men's Formal Shoes",
    description: "Classy shoes for formal wear",
    price: 89.99,
    discountPercentage: 20,
    rating: 4.6,
    stock: 100,
    brand: "Brand M",
    category: "Men",
    subcategory: "Formal Shoes",
    thumbnail: "https://example.com/thumbnail13.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQMf_hq4W37jIhJndIFyMpd7f810mmuszWQmteCuRNGw6iwheaFYGi-ogNu4rhUmqagGt6QNZiWGiT6NQuzPv2bkX2ZDg63AR3IoyxqbFY--ApeylvTG7EoqQ"
  },
  {
    id: 14,
    title: "Men's Belt",
    description: "Leather belt for formal and casual wear",
    price: 29.99,
    discountPercentage: 10,
    rating: 4.3,
    stock: 180,
    brand: "Brand N",
    category: "Men",
    subcategory: "Belts",
    thumbnail: "https://example.com/thumbnail14.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR5xFs_rZf7CELM1GMnGf3zOdhznLQwpIp8oMjlf9IRnfxDi7E1UJaWpOP4tqxjEN7awVGJYa1cebjhMME9sVXNijLY6sfs3kPGtSH5dpbJybANT8euYagwu7uK"
  },
  {
    id: 15,
    title: "Men's Sweatpants",
    description: "Comfortable sweatpants for gym and casual wear",
    price: 39.99,
    discountPercentage: 15,
    rating: 4.2,
    stock: 200,
    brand: "Brand O",
    category: "Men",
    subcategory: "Pants",
    thumbnail: "https://example.com/thumbnail15.jpg",
    images: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTlokkIj0RwXcRFYS_fo7SGMdbcuHEapp9UivLlCmNKFbM3k0elSrAuPZJJQ7w5LF9ePNbrada003EO_P0KWAjX2OTeEQg7frP2JhZh-FW-9VMgQ1biBr87zQ&usqp=CAc"
  },
  {
    id: 16,
    title: "Men's Sneakers",
    description: "Trendy sneakers for casual outings",
    price: 69.99,
    discountPercentage: 12,
    rating: 4.5,
    stock: 90,
    brand: "Brand P",
    category: "Men",
    subcategory: "Casual Shoes",
    thumbnail: "https://example.com/thumbnail16.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTDDGBIIPFnBeqUpFdx63WEcVLKpe7XDK6moUClNaGlBRGth90GXz30_33UIoTvs2lnvI5kGkfo6WUQbdghhGPWuUVWNCUGVK0dyVgP-g3Kigg1r-dneLnHNA"
  },
  {
    id: 17,
    title: "Men's Sports Shorts",
    description: "Perfect for gym or outdoor activities",
    price: 19.99,
    discountPercentage: 20,
    rating: 4.4,
    stock: 150,
    brand: "Brand Q",
    category: "Men",
    subcategory: "Shorts",
    thumbnail: "https://example.com/thumbnail17.jpg",
    images: "https://images.meesho.com/images/products/505151971/q0e0e_1200.jpg"
  },
  {
    id: 18,
    title: "Men's Cap",
    description: "Casual cap to protect from the sun",
    price: 14.99,
    discountPercentage: 10,
    rating: 4.1,
    stock: 300,
    brand: "Brand R",
    category: "Men",
    subcategory: "Headwear",
    thumbnail: "https://example.com/thumbnail18.jpg",
    images: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTJqcPjfKoreXvslFV5_FIGy20a8uARlwjg_ExC6fYbCTMGMrY22QQBI60hH_NhsWwyEZupGs1TRiDPTv759eIiJ3fCojyqaUdVZec-NoVBvSunNNoxDkdxnUs"
  },
  {
    id: 19,
    title: "Men's Slippers",
    description: "Comfortable slippers for home use",
    price: 19.99,
    discountPercentage: 5,
    rating: 4.2,
    stock: 250,
    brand: "Brand S",
    category: "Men",
    subcategory: "Slippers",
    thumbnail: "https://example.com/thumbnail19.jpg",
    images: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTMa7LwLk-SHRkRH44PFabiWXR_51ZRvjQ8tTRdkNUH1bW_UGdrTMrLogwZfIBr3TW6P-n1ogVmYC_zOsJ1MpCU_QYETv1oyoza_8QaLnCF8fQ7tfeAVWGvk6Wh"
  },
  {
    id: 20,
    title: "Men's Gym Bag",
    description: "Durable gym bag for all your workout essentials",
    price: 49.99,
    discountPercentage: 15,
    rating: 4.6,
    stock: 100,
    brand: "Brand T",
    category: "Men",
    subcategory: "Bags",
    thumbnail: "https://example.com/thumbnail20.jpg",
    images: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTkvjmohaIrGS_mQi4o0O-Rl2IcV2Hv4rY0bDUMwZBJlgkhsFF1RMfL0pi6QDK7YyQHBfkyzZMnGb0KEK-_H3Z0osCur2BIl6boe_hEw_ScBLMgPyRnIC27&usqp=CAc"
  },
  {
    id: 1,
    title: 'Kids Cotton T-Shirt',
    description: 'Soft and breathable cotton T-shirt for kids',
    price: 15.99,
    discountPercentage: 5,
    rating: 4.6,
    stock: 200,
    brand: 'TinyTrends',
    category: 'Kids',
    subcategory: 'T-Shirts',
    thumbnail: 'https://example.com/thumb1.jpg',
    images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYBnEMYOpr2H5Pq5l8Q2gVOrRFbMfbstmAnA&s'
  },
  {
    id: 2,
    title: 'Kids Denim Jeans',
    description: 'Durable denim jeans with elastic waist',
    price: 25.50,
    discountPercentage: 12,
    rating: 4.3,
    stock: 180,
    brand: 'MiniStyle',
    category: 'Kids',
    subcategory: 'Bottoms',
    thumbnail: 'https://example.com/thumb2.jpg',
    images: 'https://5.imimg.com/data5/SELLER/Default/2024/8/446743523/DI/VJ/FG/105433423/3-500x500.jpg'
  },
  {
    id: 3,
    title: 'Kids Hooded Jacket',
    description: 'Warm hooded jacket perfect for winters',
    price: 35.00,
    discountPercentage: 15,
    rating: 4.8,
    stock: 95,
    brand: 'KiddoWear',
    category: 'Kids',
    subcategory: 'Outerwear',
    thumbnail: 'https://example.com/thumb3.jpg',
    images: 'https://thehouseofrare.com/cdn/shop/files/WRICKBLACK_5_-X-Design.webp?v=1743511628'
  },
  {
    id: 4,
    title: 'Kids Ethnic Kurta Set',
    description: 'Traditional wear for kids with modern touch',
    price: 29.99,
    discountPercentage: 10,
    rating: 4.5,
    stock: 130,
    brand: 'LittleRoyal',
    category: 'Kids',
    subcategory: 'Ethnic',
    thumbnail: 'https://example.com/thumb4.jpg',
    images: 'https://fcity.in/images/products/429820080/0x2bi_256.jpg'
  },
  {
    id: 5,
    title: 'Kids Party Dress',
    description: 'Stylish dress for birthday and parties',
    price: 40.00,
    discountPercentage: 20,
    rating: 4.7,
    stock: 75,
    brand: 'GlowKids',
    category: 'Kids',
    subcategory: 'Dresses',
    thumbnail: 'https://example.com/thumb5.jpg',
    images: 'https://www.foreverkidz.in/cdn/shop/files/Blushing_Pink_Party_Dress-5015016.jpg?crop=center&height=2100&v=1730113131&width=1500'
  },
  {
    id: 6,
    title: 'Kids Sports Shoes',
    description: 'Comfortable and stylish shoes for running',
    price: 22.49,
    discountPercentage: 10,
    rating: 4.4,
    stock: 120,
    brand: 'ActiveFeet',
    category: 'Kids',
    subcategory: 'Footwear',
    thumbnail: 'https://example.com/thumb6.jpg',
    images: 'https://images.meesho.com/images/products/429457678/y77pq_512.webp'
  },
  {
    id: 7,
    title: 'Kids Cartoon Socks (Pack of 5)',
    description: 'Colorful cartoon printed socks',
    price: 9.99,
    discountPercentage: 5,
    rating: 4.2,
    stock: 300,
    brand: 'SockyToes',
    category: 'Kids',
    subcategory: 'Accessories',
    thumbnail: 'https://example.com/thumb7.jpg',
    images: 'https://m.media-amazon.com/images/I/61kXyC0xY0L._AC_UY1100_.jpg'
  },
  {
    id: 8,
    title: 'Kids Raincoat with Bag',
    description: 'Waterproof raincoat with matching carry bag',
    price: 18.99,
    discountPercentage: 8,
    rating: 4.5,
    stock: 60,
    brand: 'RainyFun',
    category: 'Kids',
    subcategory: 'Rainwear',
    thumbnail: 'https://example.com/thumb8.jpg',
    images: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjmUa6LlzZt_0ghayP0pIy--oQHZknky5FrA&s'
  },
  {
    id: 9,
    title: 'Kids Pajama Set',
    description: 'Cotton nightwear set with cartoon prints',
    price: 17.99,
    discountPercentage: 7,
    rating: 4.3,
    stock: 150,
    brand: 'SleepyTots',
    category: 'Kids',
    subcategory: 'Nightwear',
    thumbnail: 'https://example.com/thumb9.jpg',
    images: 'https://m.media-amazon.com/images/I/51vUVWCRh0L._AC_UY1100_.jpg'
  },
  {
    id: 10,
    title: 'Kids Winter Beanie',
    description: 'Woolen beanie to keep your child warm',
    price: 8.49,
    discountPercentage: 10,
    rating: 4.6,
    stock: 250,
    brand: 'WarmHeads',
    category: 'Kids',
    subcategory: 'Accessories',
    thumbnail: 'https://example.com/thumb10.jpg',
    images: 'https://images.meesho.com/images/products/217126472/znhqu_512.webp'
  },
  {
    id: 11,
    title: 'Kids Waterproof School Bag',
    description: 'Lightweight and waterproof bag with cartoon design',
    price: 19.99,
    discountPercentage: 12,
    rating: 4.4,
    stock: 170,
    brand: 'BaggyBuds',
    category: 'Kids',
    subcategory: 'School Essentials',
    thumbnail: 'https://example.com/thumb11.jpg',
    images: 'https://myneemoe.in/cdn/shop/files/WhatsAppImage2024-05-03at19.07.40.jpg?v=1717847325&width=1445'
  },
  {
    id: 12,
    title: 'Kids Fancy Cap',
    description: 'Cool and stylish caps for outdoor fun',
    price: 6.99,
    discountPercentage: 8,
    rating: 4.1,
    stock: 220,
    brand: 'Capsters',
    category: 'Kids',
    subcategory: 'Accessories',
    thumbnail: 'https://example.com/thumb12.jpg',
    images: 'https://i.pinimg.com/736x/1a/6d/c5/1a6dc50b245376e7d7b9636ccc0600b5.jpg'
  },
  {
    id: 13,
    title: 'Kids Printed Shorts',
    description: 'Comfortable cotton shorts for summer',
    price: 13.50,
    discountPercentage: 10,
    rating: 4.2,
    stock: 160,
    brand: 'SummerTots',
    category: 'Kids',
    subcategory: 'Bottoms',
    thumbnail: 'https://example.com/thumb13.jpg',
    images: 'https://m.media-amazon.com/images/I/71XVr3XbUtL._AC_UY1100_.jpg'
  },
  {
    id: 14,
    title: 'Kids Sweatshirt',
    description: 'Casual sweatshirt for cool evenings',
    price: 21.00,
    discountPercentage: 11,
    rating: 4.4,
    stock: 90,
    brand: 'CozyBuds',
    category: 'Kids',
    subcategory: 'Outerwear',
    thumbnail: 'https://example.com/thumb14.jpg',
    images: 'https://images.meesho.com/images/products/384645004/j7jjm_512.webp'
  },
  {
    id: 15,
    title: 'Kids Frock with Bow',
    description: 'Elegant frock with bow for girls',
    price: 32.00,
    discountPercentage: 18,
    rating: 4.6,
    stock: 85,
    brand: 'ChicPrincess',
    category: 'Kids',
    subcategory: 'Dresses',
    thumbnail: 'https://example.com/thumb15.jpg',
    images: 'https://www.mumkins.in/cdn/shop/files/girls-frock-gs17425-black-model-image.jpg?v=1685615213&width=1080'
  },
  {
    id: 16,
    title: 'Kids Slippers', 
    description: 'Soft and non-slip indoor slippers',
    price: 10.99,
    discountPercentage: 6,
    rating: 4.3,
    stock: 190,
    brand: 'TinySteps',
    category: 'Kids',
    subcategory: 'Footwear',
    thumbnail: 'https://example.com/thumb16.jpg',
    images: 'https://images.jdmagicbox.com/quickquotes/images_main/winter-warm-kids-slipper-372870949-vytbp.jpg'
  },
  {
    id: 17,
    title: 'Kids Fancy Hairband Set',
    description: 'Colorful and fancy hair accessories',
    price: 7.49,
    discountPercentage: 9,
    rating: 4.5,
    stock: 210,
    brand: 'HairHugs',
    category: 'Kids',
    subcategory: 'Accessories',
    thumbnail: 'https://example.com/thumb17.jpg',
    images: 'https://m.media-amazon.com/images/I/61PwkDQ7erL.jpg'
  },
  {
    id: 18,
    title: 'Kids Waterproof Apron',
    description: 'Apron for art, craft, and mess-free play',
    price: 11.25,
    discountPercentage: 5,
    rating: 4.2,
    stock: 100,
    brand: 'MessyPlay',
    category: 'Kids',
    subcategory: 'School Essentials',
    thumbnail: 'https://example.com/thumb18.jpg',
    images: 'https://m.media-amazon.com/images/I/812ksqmEOML._AC_UF894,1000_QL80_.jpg'
  },
  {
    id: 19,
    title: 'Kids Cartoon Gloves',
    description: 'Warm and soft gloves with cartoon patterns',
    price: 5.99,
    discountPercentage: 7,
    rating: 4.3,
    stock: 130,
    brand: 'HandyHugs',
    category: 'Kids',
    subcategory: 'Accessories',
    thumbnail: 'https://example.com/thumb19.jpg',
    images: 'https://s.alicdn.com/@sc04/kf/Hfb2cb742f43c41c893f29b7935113ac1d.jpg_300x300.jpg'
  },
  {
    id: 20,
    title: 'Kids Cotton Romper',
    description: 'Soft and stretchable rompers for toddlers',
    price: 14.99,
    discountPercentage: 10,
    rating: 4.6,
    stock: 140,
    brand: 'BabyNest',
    category: 'Kids',
    subcategory: 'Onesies',
    thumbnail: 'https://example.com/thumb20.jpg',
    images: 'https://assets.myntassets.com/w_412,q_60,dpr_2,fl_progressive/assets/images/23247256/2023/6/23/a938c33b-c553-4d01-8c39-a9832fa340d51687497249363-GREENDIGO-Infants-Kids-Conversational-Printed-Pure-Cotton-Ro-11.jpg'
  },
  {
    id: 1,
    title: 'Kids Colorful Plate Set (6 pcs)',
    description: 'Durable, BPA-free plates in fun colors',
    price: 99,
    discountPercentage: 0,
    rating: 4.7,
    stock: 300,
    brand: 'IKEA KALAS',
    category: 'Home & Kitchen',
    subcategory: 'Tableware',
    thumbnail: 'https://www.ikea.com/in/en/images/products/kalas-plate-mixed-colours__0711231_pe728125_s5.jpg',
    images: "https://images.meesho.com/images/products/478151701/n5um7_1200.jpg"
  },
  {
    id: 2,
    title: 'Children’s Apron with Chef Hat',
    description: 'White apron and chef hat set for kids',
    price: 599,
    discountPercentage: 0,
    rating: 4.6,
    stock: 150,
    brand: 'IKEA TOPPKLOCKA',
    category: 'Home & Kitchen',
    subcategory: 'Cooking Accessories',
    thumbnail: 'https://www.ikea.com/in/en/images/products/toppklocka-children-s-apron-with-chef-s-hat-white__0711232_pe728126_s5.jpg',
    images: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQaFtas4X3_wOrhMN4D8ojUVTw2ti1DcnVPGqWUdx0xFSXGpIOsiKPlcsXjgYQwseSJ0fAn5Uqv-JP23_-CgDtdmrCTf5DnEdRoPGLpgTzJsXPj0z5Md6C7aw&usqp=CAc'
  },
  {
    id: 3,
    title: 'Kids 3-Piece Cutlery Set',
    description: 'Fork, knife, and spoon set for children',
    price: 199,
    discountPercentage: 0,
    rating: 4.5,
    stock: 200,
    brand: 'IKEA SMASKA',
    category: 'Home & Kitchen',
    subcategory: 'Cutlery',
    thumbnail: 'https://www.ikea.com/in/en/images/products/smaska-3-piece-cutlery-set-mixed-colours__0711233_pe728127_s5.jpg',
    images: 'https://m.media-amazon.com/images/I/71heSi1ofXL.jpg'
  },
  {
    id: 4,
    title: 'Children’s Knife and Peeler Set',
    description: 'Safe kitchen tools for kids',
    price: 799,
    discountPercentage: 0,
    rating: 4.4,
    stock: 100,
    brand: 'IKEA SMÅBIT',
    category: 'Home & Kitchen',
    subcategory: 'Cooking Tools',
    thumbnail: 'https://www.ikea.com/in/en/images/products/smabit-2-piece-knife-set__0711234_pe728128_s5.jpg',
    images: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSbkXcXWIytm_L2i1tun5VZaJdwHQhbpD0p9m_awaAKILuHMzVHsxwk_u4DPzz8dBRR3zYjoNRD_my9UmUMjQS2F2HT5vrHU2_ZcGyNzxT6r5-s8BdKkdwJ'
  },
  {
    id: 5,
    title: 'Kids Lunch Box with Lid',
    description: 'Colorful lunch box for school',
    price: 149,
    discountPercentage: 0,
    rating: 4.3,
    stock: 250,
    brand: 'IKEA SMASKA',
    category: 'Home & Kitchen',
    subcategory: 'Lunch Boxes',
    thumbnail: 'https://www.ikea.com/in/en/images/products/smaska-lunch-box-with-lid-mixed-colours__0711235_pe728129_s5.jpg',
    images: 'https://m.media-amazon.com/images/I/71y1s+S0taL.jpg'
  },
  {
    id: 6,
    title: 'Kids Mug Set (6 pcs)',
    description: 'Durable mugs in assorted colors',
    price: 99,
    discountPercentage: 0,
    rating: 4.6,
    stock: 180,
    brand: 'IKEA KALAS',
    category: 'Home & Kitchen',
    subcategory: 'Drinkware',
    thumbnail: 'https://www.ikea.com/in/en/images/products/kalas-mug-mixed-colours__0711236_pe728130_s5.jpg',
    images: 'https://m.media-amazon.com/images/I/61PfKYhd-FL.jpg'
  },
  {
    id: 7,
    title: 'Children’s Place Mat',
    description: 'Non-slip mat for mealtime',
    price: 149,
    discountPercentage: 0,
    rating: 4.2,
    stock: 220,
    brand: 'IKEA MATVRÅ',
    category: 'Home & Kitchen',
    subcategory: 'Table Accessories',
    thumbnail: 'https://www.ikea.com/in/en/images/products/matvra-place-mat__0711237_pe728131_s5.jpg',
    images: 'https://www.ikea.com/in/en/images/products/groenfink-place-mat-multicolour__1337851_pe948152_s5.jpg?f=s'
  },
  {
    id: 8,
    title: 'Kids Bowl Set (6 pcs)',
    description: 'Colorful bowls for children',
    price: 99,
    discountPercentage: 0,
    rating: 4.5,
    stock: 300,
    brand: 'IKEA KALAS',
    category: 'Home & Kitchen',
    subcategory: 'Tableware',
    thumbnail: 'https://www.ikea.com/in/en/images/products/kalas-bowl-mixed-colours__0711238_pe728132_s5.jpg',
    images: 'https://5.imimg.com/data5/SELLER/Default/2024/8/446908431/EE/OA/QT/55776541/1-500x500.jpg'
  },
  {
    id: 9,
    title: 'Children’s Storage Box with Lid',
    description: 'Organize toys and kitchen items',
    price: 399,
    discountPercentage: 0,
    rating: 4.3,
    stock: 150,
    brand: 'IKEA TJENA',
    category: 'Home & Kitchen',
    subcategory: 'Storage',
    thumbnail: 'https://www.ikea.com/in/en/images/products/tjena-storage-box-with-lid-white__0711239_pe728133_s5.jpg',
    images: 'https://www.kuberindustries.co.in/uploads/kuberindustries/products/kuber-industries-storage-box--square-toy-storage-box--wardrobe-organizer-for-clothes-books-toys--sta-5898281178835404_l.jpg'
  },
  {
    id: 10,
    title: 'Kids Step Stool',
    description: 'Helps kids reach kitchen counters safely',
    price: 499,
    discountPercentage: 0,
    rating: 4.7,
    stock: 100,
    brand: 'IKEA FORSIKTIG',
    category: 'Home & Kitchen',
    subcategory: 'Furniture',
    thumbnail: 'https://www.ikea.com/in/en/images/products/forsiktig-children-s-step-stool-white-green__0711240_pe728134_s5.jpg',
    images: 'https://i.pinimg.com/564x/85/bf/c9/85bfc994be93f9e7c5e27d19d52e9052.jpg'
  },
  {
    id: 11,
    title: 'Kids Cooking Set (42 pcs)',
    description: 'Pretend play kitchen set with lights and sounds',
    price: 2999,
    discountPercentage: 13,
    rating: 4.5,
    stock: 80,
    brand: 'Dream Home',
    category: 'Home & Kitchen',
    subcategory: 'Pretend Play',
    thumbnail: 'https://snooplay.in/cdn/shop/products/dream-home-kitchen-set.jpg',
    images: 'https://m.media-amazon.com/images/I/61AhxCYHk2L._AC_UF1000,1000_QL80_.jpg'
  },
  {
    id: 12,
    title: 'Barbie Kitchen and Dining Play Set (24 pcs)',
    description: 'Stainless steel kitchen set for kids',
    price: 1899,
    discountPercentage: 0,
    rating: 4.6,
    stock: 120,
    brand: 'Ramson',
    category: 'Home & Kitchen',
    subcategory: 'Pretend Play',
    thumbnail: 'https://ramsonind.com/wp-content/uploads/2020/07/barbie-kitchen-set.jpg',
    images: 'https://images-cdn.ubuy.co.in/646ef0c8b8eee757be05e3a4-barbie-stovetop-to-tabletop-deluxe.jpg'
  },
  {
    id: 13,
    title: 'Unicorn Kitchen Play Set',
    description: 'Colorful kitchen set with utensils',
    price: 1399,
    discountPercentage: 0,
    rating: 4.4,
    stock: 90,
    brand: 'Ramson',
    category: 'Home & Kitchen',
    subcategory: 'Pretend Play',
    thumbnail: 'https://ramsonind.com/wp-content/uploads/2020/07/unicorn-kitchen-set.jpg',
    images: 'https://m.media-amazon.com/images/I/716Eq0GvkPL._AC_UF1000,1000_QL80_.jpg'
  },
  {
    id: 14,
    title: 'Kids Cooking and Baking Supplies Set',
    description: '31-piece real cooking set for kids',
    price: 2499,
    discountPercentage: 0,
    rating: 4.7,
    stock: 70,
    brand: 'PERLLI',
    category: 'Home & Kitchen',
    subcategory: 'Cooking Tools',
    thumbnail: 'https://m.media-amazon.com/images/I/81Wc1vN6YzL._SL1500_.jpg',
    images: 'https://m.media-amazon.com/images/I/71UtSClD71L.jpg'
  },
  {
    id: 15,
    title: 'Kids Fruit Cutting Play Set',
    description: 'Realistic sliceable fruits and vegetables',
    price: 580,
    discountPercentage: 0,
    rating: 4.3,
    stock: 200,
    brand: 'PLUSPOINT',
    category: 'Home & Kitchen',
    subcategory: 'Pretend Play',
    thumbnail: 'https://m.media-amazon.com/images/I/71Hc0vP9G1L._SL1500_.jpg',
    images: 'https://m.media-amazon.com/images/I/81PAWfXFkEL.jpg'
  },
  {
    id: 16,
    title: 'Kids Dinner Set with Spoon & Fork',
    description: 'Complete dinner set for kids including plate, spoon, and fork',
    price: 799,
    discountPercentage: 0,
    rating: 4.6,
    stock: 120,
    brand: 'TinyBites',
    category: 'Home & Kitchen',
    subcategory: 'Tableware',
    thumbnail: 'https://example.com/thumb16.jpg',
    images: 'https://5.imimg.com/data5/SELLER/Default/2023/9/348319006/LT/OE/KI/111761404/kids-plate-and-spoon-set-500x500.jpg'
  },
  {
    id: 17,
    title: 'Children’s Snack Box with Dividers',
    description: 'Compact snack box with compartments for easy packing',
    price: 299,
    discountPercentage: 0,
    rating: 4.3,
    stock: 180,
    brand: 'HappySnack',
    category: 'Home & Kitchen',
    subcategory: 'Lunch Boxes',
    thumbnail: 'https://example.com/thumb17.jpg',
    images: 'https://m.media-amazon.com/images/I/61x9fJqkpfL._AC_UF894,1000_QL80_.jpg'
  },
  {
    id: 18,
    title: 'Children’s Pot and Pan Set',
    description: 'Toy cooking set for imaginative play with mini pots and pans',
    price: 399,
    discountPercentage: 0,
    rating: 4.2,
    stock: 150,
    brand: 'PlayMaster',
    category: 'Home & Kitchen',
    subcategory: 'Pretend Play',
    thumbnail: 'https://example.com/thumb18.jpg',
    images: 'https://5.imimg.com/data5/ECOM/Default/2023/6/316952828/EF/FG/LS/9422220/16pcs-mini-kitchen-children-cookware-pot-pan-kids-pretend-cook-play-toy-simulation-cooking-utensils-toy.jpg'
  },
  {
    id: 19,
    title: 'Kids Pillow and Blanket Set',
    description: 'Soft and cozy pillow and blanket combo for kids',
    price: 999,
    discountPercentage: 0,
    rating: 4.8,
    stock: 200,
    brand: 'SnuggleBuddies',
    category: 'Home & Kitchen',
    subcategory: 'Bedding',
    thumbnail: 'https://example.com/thumb19.jpg',
    images: 'https://m.media-amazon.com/images/I/61sSosQJc1L.jpg'
  },
  {
    id: 20,
    title: 'Kids Portable Water Bottle',
    description: 'Leak-proof, colorful water bottle for school and outdoor activities',
    price: 249,
    discountPercentage: 0,
    rating: 4.4,
    stock: 250,
    brand: 'ThirstQuench',
    category: 'Home & Kitchen',
    subcategory: 'Drinkware',
    thumbnail: 'https://example.com/thumb20.jpg',
    images: 'https://myborosil.com/cdn/shop/files/my-borosil-water-bottles-900-ml-gosport-football-29838171046026_2024-05-24T10_23_18.063Z.png'
  },
  {
    id: 1,
    title: 'WOW Skin Science Kids Coconut 3-in-1 Tip to Toe Wash',
    description: 'Shampoo, conditioner, and body wash with coconut fragrance',
    price: 399,
    discountPercentage: 29,
    rating: 4.5,
    stock: 569,
    brand: 'WOW Skin Science',
    category: 'Beauty & Health',
    subcategory: 'Body Wash',
    thumbnail: 'https://example.com/thumb1.jpg',
    images: 'https://adn-static1.nykaa.com/media/wysiwyg/8904311900719kidscoconutstep1.jpg?tr=w-400,pr-true'
  },
  {
    id: 2,
    title: "Johnson's Active Kids Shiny Drops Shampoo",
    description: 'Gentle shampoo for shiny and smooth hair',
    price: 270,
    discountPercentage: 0,
    rating: 4.6,
    stock: 2333,
    brand: "Johnson's",
    category: 'Beauty & Health',
    subcategory: 'Shampoo',
    thumbnail: 'https://example.com/thumb2.jpg',
    images: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkubjN4Sp5PbzHjonlbuTZfz3aWxr6pfAzAw&s'
  },
  {
    id: 3,
    title: 'Biotique Bio Apple Blossom Shampoo For Disney Kids',
    description: 'Natural shampoo with apple blossom fragrance',
    price: 169,
    discountPercentage: 0,
    rating: 4.4,
    stock: 1426,
    brand: 'Biotique',
    category: 'Beauty & Health',
    subcategory: 'Shampoo',
    thumbnail: 'https://example.com/thumb3.jpg',
    images: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwQcWOvVtTpWsaaarQCgcn5F99R4S3uavt8w&s'
  },
  {
    id: 4,
    title: 'Sebamed Baby Shampoo',
    description: 'pH 5.5 shampoo with camomile and natural moisturizers',
    price: 1060,
    discountPercentage: 4,
    rating: 4.7,
    stock: 526,
    brand: 'Sebamed',
    category: 'Beauty & Health',
    subcategory: 'Shampoo',
    thumbnail: 'https://example.com/thumb4.jpg',
    images: 'https://rukminim2.flixcart.com/image/850/1000/xif0q/shampoo/j/g/l/-original-imah58xsgz27wyrm.jpeg?q=90&crop=false'
  },
  {
    id: 5,
    title: 'WOW Skin Science Kids Ban-the-Sun Sunscreen Cream SPF 30+',
    description: 'Sunscreen cream with SPF 30+ protection',
    price: 349,
    discountPercentage: 14,
    rating: 4.5,
    stock: 1110,
    brand: 'WOW Skin Science',
    category: 'Beauty & Health',
    subcategory: 'Sunscreen',
    thumbnail: 'https://example.com/thumb5.jpg',
    images: 'https://m.media-amazon.com/images/I/71ZmZ3zIpzL._AC_UF1000,1000_QL80_.jpg'
  },
  {
    id: 6,
    title: 'Sebamed Children\'s Shampoo',
    description: 'Gentle shampoo for children with pH 5.5',
    price: 200,
    discountPercentage: 0,
    rating: 4.6,
    stock: 1259,
    brand: 'Sebamed',
    category: 'Beauty & Health',
    subcategory: 'Shampoo',
    thumbnail: 'https://example.com/thumb6.jpg',
    images: 'https://rukminim2.flixcart.com/image/850/1000/xif0q/shampoo/j/g/l/-original-imah58xsgz27wyrm.jpeg?q=90&crop=false'
  },
  {
    id: 7,
    title: 'Biotique Disney Princess Almond Nourishing Soap',
    description: 'Almond soap for nourishing skin',
    price: 55,
    discountPercentage: 0,
    rating: 4.3,
    stock: 1725,
    brand: 'Biotique',
    category: 'Beauty & Health',
    subcategory: 'Soap',
    thumbnail: 'https://example.com/thumb7.jpg',
    images: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/0/4/04155dc8906009458557_1.jpg'
  },
  {
    id: 8,
    title: 'WOW Skin Science Kids Strawberry 3-in-1 Tip to Toe Wash',
    description: 'Shampoo, conditioner, and body wash with strawberry fragrance',
    price: 399,
    discountPercentage: 22,
    rating: 4.4,
    stock: 823,
    brand: 'WOW Skin Science',
    category: 'Beauty & Health',
    subcategory: 'Body Wash',
    thumbnail: 'https://example.com/thumb8.jpg',
    images: 'https://images-static.nykaa.com/media/catalog/product/1/d/1d9cb75KIDS_WASH_STRAWBERRY_1.jpg?tr=w-500'
  },
  {
    id: 9,
    title: 'Oral-B Kids Toothbrush - Extra Soft (Pack of 3)',
    description: 'Extra soft toothbrushes for kids',
    price: 75,
    discountPercentage: 20,
    rating: 4.5,
    stock: 769,
    brand: 'Oral-B',
    category: 'Beauty & Health',
    subcategory: 'Oral Care',
    thumbnail: 'https://example.com/thumb9.jpg',
    images: 'https://images-static.nykaa.com/media/catalog/product/a/4/a456ecb4902430905183_2609_2.jpg?tr=w-500'
  },
  {
    id: 10,
    title: 'Mamaearth 100% Natural Berry Blast Kids Toothpaste',
    description: 'Natural toothpaste with berry flavor',
    price: 149,
    discountPercentage: 5,
    rating: 4.6,
    stock: 1275,
    brand: 'Mamaearth',
    category: 'Beauty & Health',
    subcategory: 'Oral Care',
    thumbnail: 'https://example.com/thumb10.jpg',
    images: 'https://m.media-amazon.com/images/I/61tXbDKE4wL._AC_UF1000,1000_QL80_.jpg'
  },
  {
    id: 11,
    title: 'HealthBest Kidbest Bodywash for Kids - Watermelon Flavor',
    description: 'Anti-bacterial bodywash for kids with watermelon flavor',
    price: 559,
    discountPercentage: 6,
    rating: 4.4,
    stock: 500,
    brand: 'HealthBest',
    category: 'Beauty & Health',
    subcategory: 'Body Wash',
    thumbnail: 'https://example.com/thumb11.jpg',
    images: 'https://www.healthbest.com/cdn/shop/files/kids-body-washkids-cosmetic-256492.webp?v=1738671207&width=416'
  },
  {
    id: 12,
    title: 'HealthBest Kidbest Body Lotion for Kids - Watermelon Flavor',
    description: 'Body lotion for kids with watermelon flavor',
    price: 509,
    discountPercentage: 7,
    rating: 4.5,
    stock: 500,
    brand: 'HealthBest',
    category: 'Beauty & Health',
    subcategory: 'Body Lotion',
    thumbnail: 'https://example.com/thumb12.jpg',
    images: 'https://m.media-amazon.com/images/I/71TUaZphZlL.jpg'
  },
  {
    id: 13,
    title: 'HealthBest Kidbest Conditioner for Kids - Watermelon Flavor',
    description: 'Hair conditioner for kids with watermelon flavor',
    price: 509,
    discountPercentage: 7,
    rating: 4.3,
    stock: 500,
    brand: 'HealthBest',
    category: 'Beauty & Health',
    subcategory: 'Hair Care',
    thumbnail: 'https://example.com/thumb13.jpg',
    images: 'https://www.netmeds.com/images/product-v1/400x400/982291/healthbest_kidbest_3_13_years_conditioner_watermelon_flavour_200_gm_3_0.webp'
  },
  {
    id: 14,
    title: 'HealthBest Infabest Hematinic (Iron) Drops for Toddlers',
    description: 'Iron and zinc supplement drops for toddlers',
    price: 329,
    discountPercentage: 6,
    rating: 4.6,
    stock: 500,
    brand: 'HealthBest',
    category: 'Beauty & Health',
    subcategory: 'Supplements',
    thumbnail: 'https://example.com/thumb14.jpg',
    images: 'https://rukminim2.flixcart.com/image/850/1000/xif0q/vitamin-supplement/u/d/q/60-infabest-multivitamins-minerals-drops-for-toddlers-each-30ml-original-imagzeuwgwhhsbpu.jpeg?q=90&crop=false'
  },
  {
    id: 15,
    title: 'HealthBest Infabest Drops - Multivitamins with Vitamin D3 & Zinc',
    description: 'Multivitamin drops for kids and toddlers',
    price: 419,
    discountPercentage: 6,
    rating: 4.5,
    stock: 500,
    brand: 'HealthBest',
    category: 'Beauty & Health',
    subcategory: 'Supplements',
    thumbnail: 'https://example.com/thumb15.jpg',
    images: 'https://m.media-amazon.com/images/I/81hNvXkGm5S.jpg'
  },
  {
    id: 16,
    title: 'Whimsy Makeup Kit for Kids - Pack of 14',
    description: 'Skin-friendly makeup kit designed for kids and preteens',
    price: 2499,
    discountPercentage: 0,
    rating: 4.7,
    stock: 100,
    brand: 'Whimsy',
    category: 'Beauty & Health',
    subcategory: 'Makeup',
    thumbnail: 'https://example.com/thumb16.jpg',
    images: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSF8aSJnUy3iORzaTEG1hLfEcXm59o3Xe3eMGXRcnr2PG2lhWQtKmKr8IMxLe5DvTCMYp8vBKaTd0bNXmR6DxnZ1Qv-9AiZ6s4GPOKNf6QbGcKYpNnVt9yw&usqp=CAc'
  },
  {
    id: 17,
    title: 'Whimsy Vitamin-E Face Wash For Kids and Teens',
    description: 'Gentle face wash with Vitamin E for kids and teens',
    price: 219,
    discountPercentage: 0,
    rating: 4.5,
    stock: 100,
    brand: 'Whimsy',
    category: 'Beauty & Health',
    subcategory: 'Face Wash',
    thumbnail: 'https://example.com/thumb17.jpg',
    images: 'https://m.media-amazon.com/images/I/61PuEfRollL.jpg'
  },
  {
    id: 18,
    title: "Whimsy Aloe Vera BodyWash for Kids and Teens",
    description: "Aloe vera body wash suitable for kids and teens",
    price: 236,
    discountPercentage: 0,
    rating: 4.4,
    stock: 100,
    brand: "Whimsy",
    category: "Beauty & Health",
    subcategory: "Body Wash",
    thumbnail: "https://example.com/thumb18.jpg",
    images:'https://m.media-amazon.com/images/I/51redVEnv5L._AC_UF1000,1000_QL80_.jpg'
  },
  {
    id: 19,
    title: 'Mom & World Kids Face Wash',
    description: 'Gentle face wash for kids with natural ingredients',
    price: 399,
    discountPercentage: 13,
    rating: 4.5,
    stock: 297,
    brand: 'Mom & World',
    category: 'Beauty & Health',
    subcategory: 'Face Wash',
    thumbnail: 'https://example.com/thumb19.jpg',
    images: 'https://rukminim2.flixcart.com/image/850/1000/xif0q/face-wash/s/o/o/120-kids-face-wash-tear-free-120ml-no-sls-paraben-mom-world-original-imah9qrkjaase7py.jpeg?q=20&crop=false'
  },
  {
    id: 20,
    title: 'Mom & World Mineral Based Kids Sunscreen Spray SPF 50',
    description: 'Mineral-based sunscreen spray with SPF 50 for kids',
    price: 449,
    discountPercentage: 18,
    rating: 4.6,
    stock: 325,
    brand: 'Mom & World',
    category: 'Beauty & Health',
    subcategory: 'Sunscreen',
    thumbnail: 'https://example.com/thumb20.jpg',
    images: 'https://m.media-amazon.com/images/I/71Hg+c3DmhL._AC_UF894,1000_QL80_.jpg'
  }
  

]


export { product, category }






